// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ranking.Data;

namespace Ranking.Data.Migrations
{
    [DbContext(typeof(RankingContext))]
    [Migration("20190725202245_Initia migration")]
    partial class Initiamigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ranking.Data.Entities.Confederations", b =>
                {
                    b.Property<int>("ConfederationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("Weight");

                    b.HasKey("ConfederationID");

                    b.ToTable("Confederations");
                });

            modelBuilder.Entity("Ranking.Data.Entities.MatchTypes", b =>
                {
                    b.Property<int>("MatchTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("Weight");

                    b.HasKey("MatchTypeID");

                    b.ToTable("MatchTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
